# We use placeholder name/tag because CalVer is not supported by release drafter. 
# Maybe it can be automated, but for now we will type the CalVer (YY.MM.XX) manually.
name-template: 'DRAFT: INSERT_VERSION_HERE'
tag-template: 'DRAFT_VERSION' 

categories:
  - title: 'CoreSDK'
    labels:
      - 'package-core-sdk'

  - title: 'Motion Toolkit'
    labels:
      - 'package-motion-toolkit'

template: |
  # Changelog
  ## General changes
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$NEW_TAG