changelog:
  categories:
    - title: "📦 CoreSDK"
      labels:
        - "core-sdk"
    
    - title: "📦 Motion Toolkit"
      labels:
        - "motion-toolkit"
        
    - title: "🛠 Other Changes"
      labels:
        - "*"
